// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://votqhlmjjmqviguycznf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZvdHFobG1qam1xdmlndXljem5mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1MTMzNjksImV4cCI6MjA2MzA4OTM2OX0.ByrnvIS54ORPIgCuRMjGp2n_tbUnPesIUPYmsEN-G9U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);