
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://votqhlmjjmqviguycznf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZvdHFobG1qam1xdmlndXljem5mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1MTMzNjksImV4cCI6MjA2MzA4OTM2OX0.ByrnvIS54ORPIgCuRMjGp2n_tbUnPesIUPYmsEN-G9U";

// Initialisation du client avec des options explicites pour garantir un comportement cohérent
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Vérification du bucket avatars pour assurer qu'il est accessible
const checkAvatarsBucket = async () => {
  try {
    const { data: buckets, error } = await supabase.storage.listBuckets();
    
    if (error) {
      console.error("Erreur lors de la vérification des buckets:", error);
      return;
    }
    
    const avatarsBucket = buckets?.find(bucket => bucket.name === 'avatars');
    
    if (avatarsBucket) {
      console.log("Bucket 'avatars' trouvé avec succès");
    } else {
      console.warn("Le bucket 'avatars' n'existe pas. Les uploads d'images ne fonctionneront pas correctement.");
    }
  } catch (error) {
    console.error('Erreur lors de la vérification des buckets:', error);
  }
};

// Exécuter la vérification au chargement
checkAvatarsBucket();
